name: fa_flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  device_info: ^2.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  internet_connection_checker: ^0.0.1+3
  path_provider: ^2.0.9
  uuid: ^3.0.6
  dartx: ^1.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20 
  bot_toast: ^4.0.1
  imei_plugin: ^1.2.0
  
  # Get family
  get_it: ^7.2.0

  # Camera Modules
  camera: ^0.9.4+16
  keyboard_visibility: ^0.5.6

  # Sembast
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1

  # Api service
  fa_flutter_api_client:
    git:
      url: https://github.com/FieldAssist/fa_flutter_api_client.git
      ref: main

  collection: ^1.15.0

  fa_flutter_ui_kit:
    git:
      url: https://github.com/FieldAssist/fa_flutter_ui_kit.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
